### ISSUE TITLE
Make the daily mail look sexy !!

### ISSUE THREAD

**Issue by vdaubry** [Linkastor/Linkastor#12]
We should scrap the meta-og from the page to get more infos about the page :

Image
Description
Website name, etc

With these infos we could display the links as boxes, something like pinterest.

**Comment by tibo** [comment]
@vdaubry got any idea on this one?

**Comment by vdaubry** [comment]
Since we're also going to pull links from other sources (twitter, etc) we're going to need to get all these infos from the backend. 
So i would start by creating a Ruby class that takes an url as param and fetches infos about the page :
- Image (lets start with the og:image , then we could be a little more smart and take the largest image on the page)
- Description (i would also start by looking for an og:description, and if we cannot find any take the first sentence of the page)
- Website image / author image

With this 3 infos i think we can try to do something à la Pinterest

**Comment by vdaubry** [comment]
We can also copy the way scoop.it displays articles : very large tiles with a longer description (5 to 10 lines) :

![screen shot 2015-06-25 at 10 47 04](https://cloud.githubusercontent.com/assets/498298/8350601/4cd14064-1b27-11e5-9316-9a00c613a921.png)

**Comment by vdaubry** [comment]
We could take ideas from flipboard, to show links on the web page (this display it wont work in a mail)
