### ISSUE TITLE
Move the Linkastor twitter app to a shared account

### ISSUE THREAD

**Issue by vdaubry** [Linkastor/Linkastor#14]
Currently the twiter app belongs to my personal twitter account and you cannot invite people.
We should create a twitter account for Linkastor and use it as owner of the twitter app.

**Comment by tibo** [comment]
good idea

**Comment by vdaubry** [comment]
To create a account with app you need to provide a phone number not associated with another account...
Do you have one ?

**Comment by vdaubry** [comment]
I created a twitter account for linkastor : https://twitter.com/linkastor

We need a profile pic now :)

I send you the Twitter app credentials. I changed the API key and secret on Heroku, it works fine.
