### ISSUE TITLE
Remove sent invites from pending invites

### ISSUE THREAD

**Issue by tibo** [Linkastor/Linkastor#48]
Cc @vdaubry

**Comment by vdaubry** [comment]
When a user accepts an invite his email disappears from the pending invites.
We only display the list of invitation that are not yet accepted.

Do you want to change this behavior, or do you have a bug ?

**Comment by tibo** [comment]
so it's a bug.
here is a screenshot of my current view of our main group:
![screen shot 2015-07-16 at 01 43 44](https://cloud.githubusercontent.com/assets/309695/8712409/363af576-2b5c-11e5-824a-c0d24c474d4c.png)

**Comment by vdaubry** [comment]
@tibo found the bug, you can review the PR

We also need to manually update the existing invitation to set accepted to true on Heroku (will do it when i'm back in Paris, my current wifi blocks some port and i cannot open a console on Heroku)

**Comment by tibo** [comment]
@vdaubry FYI I've updated the status on all my invites so I don't see this bug anymore
